# Generated by Django 2.1.7 on 2019-03-15 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BUSINESS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_stub',
            name='parent_volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='parent_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUSINESS.business'),
        ),
    ]
