# Generated by Django 2.1.7 on 2019-03-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0001_initial'),
        ('BUSINESS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_support_stub',
            name='parent_ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.org'),
        ),
    ]
