# Generated by Django 2.1.7 on 2019-03-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0002_auto_20190322_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='item_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=8866),
        ),
    ]
