# Generated by Django 2.1.7 on 2019-03-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0001_initial'),
        ('BUSINESS', '0002_user_support_stub_parent_ngo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_support_stub',
            name='parent_volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction_stub',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BUSINESS.coupon'),
        ),
        migrations.AddField(
            model_name='transaction_stub',
            name='parent_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUSINESS.business'),
        ),
        migrations.AddField(
            model_name='transaction_stub',
            name='parent_volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='total_support_stub',
            name='parent_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUSINESS.business'),
        ),
        migrations.AddField(
            model_name='total_support_stub',
            name='parent_ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.org'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='parent_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUSINESS.business'),
        ),
    ]
