# Generated by Django 2.1.7 on 2019-03-22 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0003_auto_20190322_2146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BUSINESS', '0003_auto_20190322_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_support_stub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.FloatField(default=0.0)),
                ('total_discount_tokens', models.FloatField(default=0.0)),
                ('total_donation_tokens', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='transaction_stub',
            name='item_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=8733),
        ),
        migrations.AddField(
            model_name='user_support_stub',
            name='parent_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUSINESS.business'),
        ),
        migrations.AddField(
            model_name='user_support_stub',
            name='parent_ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.org'),
        ),
        migrations.AddField(
            model_name='user_support_stub',
            name='parent_volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
