# Generated by Django 2.1.7 on 2019-03-23 18:38

import BUSINESS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0003_auto_20190323_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=BUSINESS.models.rand_int),
        ),
    ]
