# Generated by Django 2.1.3 on 2019-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0003_auto_20190311_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_donation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction_stub',
            name='is_donation',
            field=models.BooleanField(default=True),
        ),
    ]
