# Generated by Django 2.1.7 on 2019-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0006_auto_20190322_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=2546),
        ),
    ]
