# Generated by Django 2.1.7 on 2019-03-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0008_auto_20190322_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_stub',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BUSINESS.coupon'),
        ),
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=4356),
        ),
    ]
