# Generated by Django 2.1.7 on 2019-03-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0009_auto_20190323_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='total_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=7208),
        ),
    ]
