# Generated by Django 2.1.7 on 2019-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0010_auto_20190323_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_support_stub',
            name='total_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=2040),
        ),
    ]
