# Generated by Django 2.1.7 on 2019-03-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUSINESS', '0011_auto_20190323_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pin',
            field=models.IntegerField(default=8335),
        ),
    ]
