# Generated by Django 2.1.7 on 2019-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='VO', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='volunteer_role',
            field=models.CharField(default='DI', max_length=2, null=True),
        ),
    ]
