# Generated by Django 2.1.7 on 2019-03-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_hours_stub',
            old_name='parent_volutneer',
            new_name='parent_volunteer',
        ),
    ]
