# Generated by Django 2.1.7 on 2019-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190322_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_hours_stub',
            name='total_donation_tokens',
            field=models.FloatField(default=0.0),
        ),
    ]
