# Generated by Django 2.1.7 on 2019-03-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_total_hours_stub_total_discount_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='volunteer_hour_fund',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='total_hours_stub',
            name='total_hours_fund',
            field=models.FloatField(default=0.0),
        ),
    ]
