# Generated by Django 2.1.7 on 2019-03-10 03:37

import NGO.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checks_stub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_or_out', models.BooleanField(default=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='event_registration_stub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('QR_code', models.ImageField(blank=True, null=True, upload_to=NGO.models.get_image_path)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2500)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='parent_orgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.orgs'),
        ),
        migrations.AddField(
            model_name='event_registration_stub',
            name='parent_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.events'),
        ),
    ]
