# Generated by Django 2.1.7 on 2019-03-23 18:39

import NGO.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_auto_20190323_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=NGO.models.rand_int),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=NGO.models.rand_int),
        ),
    ]
