# Generated by Django 2.1.7 on 2019-03-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0004_auto_20190322_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=5113),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=2080),
        ),
    ]
