# Generated by Django 2.1.7 on 2019-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0007_auto_20190322_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=4313),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=5216),
        ),
    ]
