# Generated by Django 2.1.7 on 2019-03-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0008_auto_20190322_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=8200),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=6166),
        ),
    ]
