# Generated by Django 2.1.7 on 2019-03-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0009_auto_20190322_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=1316),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=8377),
        ),
    ]
