# Generated by Django 2.1.7 on 2019-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0011_auto_20190323_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=6030),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=7108),
        ),
    ]
