# Generated by Django 2.1.7 on 2019-03-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0013_auto_20190323_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='total_donation_tokens',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkin',
            field=models.IntegerField(default=9260),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin_checkout',
            field=models.IntegerField(default=7194),
        ),
    ]
